FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y iptables \
    && apt-get install -y net-tools 

COPY rules.sh  /root/rules.sh

RUN chmod +x  /root/rules.sh

CMD [ "/root/ruler.sh" ]